version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data_dev:/data/db
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/api
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
    command: npm run start:dev
    depends_on:
      - db
    links:
      - db
volumes:
  mongo-data_dev:
    external: false
