version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data_prod:/data/db
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/api
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
    command: npm run start:prod
    depends_on:
      - db
    links:
      - db
volumes:
  mongo-data_prod:
    external: false
