version: '3'
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
    command: npm run start:prod
