version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/api
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
    command: npm run start:dev
