name: Nest Continous Integration

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: echo "KEY = ${{ secrets.KEY }}"
      - uses: actions/checkout@master
      - name: copy files via ssh password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # Copy all files from the repository to the remote server
            scp -r * ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/api
            # SSH into the remote server and run docker-compose up
            ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /api && docker-compose up'
