name: Nest Continous Integration

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    environment: Development
    steps:
      - uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{ secrets.USER }}@${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.PUBLIC_KEY }}
          stack_file_name: docker-compose.yml
          docker_login_password: ${{ secrets.DOCKER_REPO_PASSWORD }}
          docker_login_user: ${{ secrets.DOCKER_REPO_USERNAME }}
          docker_login_registry: ${{ steps.login-ecr.outputs.registry }}
          args: -p limestone_api_stack up -d
