name: Nest Continous Integration

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Debug
        run: |
          echo "HOST: ${{ secrets.HOST }} USER: ${{ secrets.USER }} PASSWORD: ${{ secrets.PASSWORD }}"
      - name: SSH into remote server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/$USER
            rm -rf limestone-api
            git clone https://github.com/murilo9/limestone-api.git
            cd limestone-api
            git pull
            docker-compose up -d
