name: Nest Continous Integration

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Debug
        run: |
          ssh ${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@${{ secrets.HOST }} 'echo $USER'
