name: Nest Continous Integration

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Deploy code
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /home/$USER && rm -rf limestone-api && git clone https://github.com/murilo9/limestone-api.git && cd limestone-api $$ git pull && docker-compose up -d"
